### ISSUE TITLE
Minio or S3 For Storage Logs

### ISSUE THREAD

**Issue by zafebarte** [opszero/terraform-aws-eks-airbyte#8]
Hello guys, congratulations on the work.

I'm using your solution to implement airbyte in k8s but I'm facing some difficulties with Minio, it doesn't seem to be working. I tried to deactivate and use S3 as a log storage environment, but I am also experiencing difficulties. could you help me?

![Captura de Tela 2024-08-12 às 15 27 12](https://github.com/user-attachments/assets/a8c84070-939d-4621-b8b0-b4478af8cba7)

**Comment by abhiyerra** [comment]
@zafebarte thank you for reaching out. Unfortunately, we cannot support these issues without a paid engagement with opsZero. Please schedule a call with us for next steps. https://calendly.com/opszero-llc/discovery?month=2024-08

**Comment by zafebarte** [comment]
Thanks for responding. I've already resolved it, if you want, I can open a fork here and send it updated and organized ;)

**Comment by abhiyerra** [comment]
@zafebarte sure, that would be wonderful.
